### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by Kurt-Hetrick** [Kurt-Hetrick/DEMUX_BCL2FQ#4]
need less arguments now

**Comment by bcraig110** [comment]
I'll run a test now and update README if it works as expected

**Comment by Kurt-Hetrick** [comment]
it isn't allowing other jobs on c6420-1.cidr.jhmi.edu (beth's jobs are flooding the cluster). so that's good

queuename       resv/used/tot.  load_avg        states
bigdata.q@DellR730-02.cidr.jhm  0/10/10 22.29
bigdata.q@DellR730-03.cidr.jhm  0/10/10 28.67
bigmem.q@sunrhel3.cidr.jhmi.ed  0/0/10  0.11
c6320.q@c6320-1.cidr.jhmi.edu   0/5/5   15.75
c6320.q@c6320-2.cidr.jhmi.edu   0/5/5   14.90
c6320.q@c6320-3.cidr.jhmi.edu   0/5/5   15.10
c6320.q@c6320-4.cidr.jhmi.edu   0/5/5   19.88
**c6420.q@c6420-1.cidr.jhmi.edu   0/1/21  37.71**
c6420.q@c6420-2.cidr.jhmi.edu   0/20/21 0.01
c6420.q@c6420-3.cidr.jhmi.edu   0/21/21 0.01
c6420.q@c6420-4.cidr.jhmi.edu   0/20/21 0.16
cgc.q@c6220-5.cidr.jhmi.edu     0/0/5   0.00
cgc.q@c6220-6.cidr.jhmi.edu     0/0/5   0.00
cgc.q@c6220-7.cidr.jhmi.edu     0/0/5   0.00
cgc.q@c6220-8.cidr.jhmi.edu     0/0/5   0.00
lemon.q@c6220-1.cidr.jhmi.edu   0/5/5   14.50
lemon.q@c6220-2.cidr.jhmi.edu   0/5/5   13.66
lemon.q@c6220-3.cidr.jhmi.edu   0/5/5   15.41
lemon.q@c6220-4.cidr.jhmi.edu   0/5/5   12.30
prod.q@c6100-10.cidr.jhmi.edu   0/5/5   16.38
prod.q@c6100-11.cidr.jhmi.edu   0/5/5   18.08
prod.q@c6100-12.cidr.jhmi.edu   0/5/5   18.42
prod.q@c6100-13.cidr.jhmi.edu   0/5/5   15.49
prod.q@c6100-14.cidr.jhmi.edu   0/5/5   16.91
prod.q@c6100-15.cidr.jhmi.edu   0/5/5   15.81
prod.q@c6100-16.cidr.jhmi.edu   0/5/5   17.02
prod.q@c6100-17.cidr.jhmi.edu   0/5/5   15.28
prod.q@c6100-18.cidr.jhmi.edu   0/5/5   17.43
prod.q@c6100-2.cidr.jhmi.edu    0/5/5   15.90
prod.q@c6100-21.cidr.jhmi.edu   0/5/5   16.18
prod.q@c6100-22.cidr.jhmi.edu   0/5/5   17.16
prod.q@c6100-23.cidr.jhmi.edu   0/5/5   15.56
prod.q@c6100-24.cidr.jhmi.edu   0/5/5   16.32
prod.q@c6100-5.cidr.jhmi.edu    0/5/5   15.87
prod.q@c6100-6.cidr.jhmi.edu    0/5/5   17.91
programmers.q@c6100-8.cidr.jhm  0/0/5   0.29
qtest.q@bright-test-compute01.  0/0/5   0.00
qtest.q@bright-test-compute02.  0/0/5   0.01
rhel7.q@sunrhel4.cidr.jhmi.edu  0/0/10  0.01
rnd.q@c6100-19.cidr.jhmi.edu    0/5/5   14.63
rnd.q@c6100-3.cidr.jhmi.edu     0/5/5   14.02
rnd.q@c6100-7.cidr.jhmi.edu     0/5/5   14.38

**Comment by Kurt-Hetrick** [comment]
oh nevermind...sort of. that is c6420.q which is not affected by the sequencing pipelines right now

**Comment by bcraig110** [comment]
Yeah...it's a little misleading.
qstat says it has 1/21 slots used but I wasn't able to get a qlogin for that node...so that's good.

**Comment by Kurt-Hetrick** [comment]
Brian updated
