### ISSUE TITLE
send notifications to teams

### ISSUE THREAD

**Issue by Kurt-Hetrick** [Kurt-Hetrick/DEMUX_BCL2FQ#6]
and to brian craig and khetrick email (or just to kurt hetrick). kurt will talk to brian to see what he prefers.

**Comment by Kurt-Hetrick** [comment]
kurts target channel is wes pipeline channel. will discuss with brian.

**Comment by bcraig110** [comment]
You can add both of us to the email. Always good to have multiple backups.

**Comment by Kurt-Hetrick** [comment]
thanks 👍 will do

**Comment by Kurt-Hetrick** [comment]
done
